#include QMK_KEYBOARD_H

TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
OLED_DRIVER_ENABLE = yes   # Enables the use of OLED displays
OLED_ENABLE = yes
WPM_ENABLE = yes
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
